name: AssetraIOSApp
options:
  minimumXcodeGenVersion: 2.38.0
configs:
  Debug: debug
  Release: release
settings:
  base:
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    CODE_SIGN_STYLE: Automatic
    GENERATE_INFOPLIST_FILE: YES
    PRODUCT_BUNDLE_IDENTIFIER: com.assetra.sample.iosapp

targets:
  AssetraIOSApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: ../ios
    settings:
      base:
        PRODUCT_NAME: AssetraIOSApp
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleDefault
        INFOPLIST_KEY_UIRequiresFullScreen: NO
