from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="assetra.location")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assetra.tenant")),
            ],
            options={"unique_together": {("tenant", "code")}},
        ),
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(max_length=50)),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="assetra.assetcategory")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assetra.tenant")),
            ],
            options={"unique_together": {("tenant", "code")}},
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("asset_tag", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("barcode_value", models.CharField(blank=True, max_length=255)),
                (
                    "barcode_type",
                    models.CharField(
                        choices=[("gs1", "GS1"), ("code128", "Code 128"), ("qr", "QR"), ("datamatrix", "DataMatrix")],
                        default="qr",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("in_maintenance", "In Maintenance"), ("retired", "Retired"), ("lost", "Lost")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="assetra.assetcategory")),
                ("current_location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="assetra.location")),
                ("parent_asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="assetra.asset")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assetra.tenant")),
            ],
            options={"unique_together": {("tenant", "asset_tag")}},
        ),
        migrations.CreateModel(
            name="TenantMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("operator", "Operator"), ("auditor", "Auditor"), ("read_only", "Read Only")],
                        max_length=20,
                    ),
                ),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="assetra.tenant")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tenant_memberships", to=settings.AUTH_USER_MODEL)),
            ],
            options={"unique_together": {("tenant", "user")}},
        ),
        migrations.CreateModel(
            name="AssetStateHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("assign", "Assign"),
                            ("move", "Move"),
                            ("inspect", "Inspect"),
                            ("maintain", "Maintain"),
                            ("retire", "Retire"),
                            ("scan", "Scan"),
                            ("reconcile", "Reconcile"),
                        ],
                        max_length=20,
                    ),
                ),
                ("gps_latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("gps_longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("previous_state", models.JSONField(default=dict)),
                ("new_state", models.JSONField(default=dict)),
                ("checksum", models.CharField(editable=False, max_length=64)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="history", to="assetra.asset")),
                ("location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="assetra.location")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assetra.tenant")),
            ],
        ),
        migrations.CreateModel(
            name="ScanEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_event_id", models.UUIDField(default=uuid.uuid4)),
                ("symbology", models.CharField(max_length=50)),
                ("raw_value", models.CharField(max_length=512)),
                ("decoded_payload", models.JSONField(blank=True, default=dict)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("camera", "Camera"), ("rfid", "RFID"), ("external_scanner", "External Scanner"), ("web", "Web")],
                        max_length=30,
                    ),
                ),
                ("gps_latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("gps_longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("offline_captured_at", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("validated", "Validated"), ("rejected", "Rejected")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="assetra.asset")),
                ("location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="assetra.location")),
                ("scanner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assetra.tenant")),
            ],
            options={"unique_together": {("tenant", "client_event_id")}},
        ),
        migrations.CreateModel(
            name="InventorySession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("status", models.CharField(choices=[("open", "Open"), ("closed", "Closed"), ("reconciled", "Reconciled")], default="open", max_length=20)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="assetra.location")),
                ("opened_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assetra.tenant")),
            ],
        ),
        migrations.CreateModel(
            name="InventoryCountLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("barcode_value", models.CharField(max_length=255)),
                ("expected_qty", models.IntegerField(default=1)),
                ("counted_qty", models.IntegerField(default=0)),
                ("variance_qty", models.IntegerField(default=0)),
                ("asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="assetra.asset")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="assetra.inventorysession")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assetra.tenant")),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("performed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("result_data", models.JSONField(blank=True, default=dict)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="maintenance_records", to="assetra.asset")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assetra.tenant")),
            ],
        ),
        migrations.CreateModel(
            name="InspectionRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("inspected_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="pass", max_length=100)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="inspection_records", to="assetra.asset")),
                ("inspector", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assetra.tenant")),
            ],
        ),
        migrations.CreateModel(
            name="BarcodeTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("symbology", models.CharField(choices=[("gs1", "GS1"), ("code128", "Code 128"), ("qr", "QR"), ("datamatrix", "DataMatrix")], max_length=20)),
                ("width_mm", models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ("height_mm", models.DecimalField(decimal_places=2, default=25, max_digits=8)),
                ("dpi", models.IntegerField(default=300)),
                ("text_template", models.TextField(blank=True)),
                ("zpl_template", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assetra.tenant")),
            ],
        ),
        migrations.CreateModel(
            name="BarcodeBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prefix", models.CharField(blank=True, max_length=20)),
                ("start_sequence", models.IntegerField(default=1)),
                ("end_sequence", models.IntegerField(default=100)),
                ("payload_schema", models.JSONField(blank=True, default=dict)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("generated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="assetra.barcodetemplate")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assetra.tenant")),
            ],
        ),
        migrations.CreateModel(
            name="BarcodeLabel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code_value", models.CharField(max_length=255)),
                ("render_payload", models.JSONField(blank=True, default=dict)),
                ("pdf_path", models.CharField(blank=True, max_length=255)),
                ("zpl_payload", models.TextField(blank=True)),
                ("asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="assetra.asset")),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="labels", to="assetra.barcodebatch")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assetra.tenant")),
            ],
        ),
        migrations.CreateModel(
            name="NoCodeFormDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("target_model", models.CharField(max_length=100)),
                ("schema", models.JSONField(default=dict)),
                ("required_fields", models.JSONField(blank=True, default=list)),
                ("validation_rules", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assetra.tenant")),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("version", models.IntegerField(default=1)),
                (
                    "trigger_type",
                    models.CharField(choices=[("on_scan", "On Scan"), ("on_status_change", "On Status Change"), ("on_time", "On Time")], max_length=30),
                ),
                ("entry_conditions", models.JSONField(blank=True, default=dict)),
                ("steps", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assetra.tenant")),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("success", "Success"), ("failed", "Failed")], default="pending", max_length=20)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("input_data", models.JSONField(blank=True, default=dict)),
                ("output_data", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="assetra.asset")),
                ("scan_event", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="assetra.scanevent")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assetra.tenant")),
                ("workflow", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="runs", to="assetra.workflowdefinition")),
            ],
        ),
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("direction", models.CharField(choices=[("inbound", "Inbound"), ("outbound", "Outbound")], max_length=20)),
                ("url", models.URLField()),
                ("secret", models.CharField(blank=True, max_length=200)),
                ("events", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("last_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assetra.tenant")),
            ],
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_name", models.CharField(max_length=120)),
                ("payload", models.JSONField(default=dict)),
                ("response_code", models.IntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("success", "Success"), ("failed", "Failed")], default="pending", max_length=20)),
                ("endpoint", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deliveries", to="assetra.webhookendpoint")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assetra.tenant")),
            ],
        ),
        migrations.CreateModel(
            name="IntegrationConnector",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "connector_type",
                    models.CharField(
                        choices=[
                            ("google_sheets", "Google Sheets"),
                            ("excel", "Excel"),
                            ("zapier", "Zapier"),
                            ("make", "Make"),
                            ("power_bi", "Power BI"),
                            ("tableau", "Tableau"),
                            ("grafana", "Grafana"),
                            ("postgresql", "PostgreSQL"),
                            ("mysql", "MySQL"),
                            ("sql_server", "SQL Server"),
                            ("oracle", "Oracle"),
                            ("custom", "Custom"),
                        ],
                        max_length=30,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assetra.tenant")),
            ],
        ),
        migrations.CreateModel(
            name="DeviceProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("platform", models.CharField(choices=[("android", "Android"), ("ios", "iOS"), ("web", "Web")], max_length=20)),
                ("device_identifier", models.CharField(max_length=120)),
                ("sdk_features", models.JSONField(blank=True, default=dict)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assetra.tenant")),
            ],
            options={"unique_together": {("tenant", "device_identifier")}},
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("enabled", models.BooleanField(default=False)),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assetra.tenant")),
            ],
            options={"unique_together": {("tenant", "key")}},
        ),
        migrations.CreateModel(
            name="IndustryPreset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("preset_type", models.CharField(choices=[("medical", "Medical"), ("maintenance", "Maintenance"), ("general", "General")], max_length=20)),
                ("config", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assetra.tenant")),
            ],
        ),
    ]
